### ISSUE TITLE
Any Streamlink Docker image available?

### ISSUE THREAD

**Issue by dnaranjor** [cgomesu/tvhlink#1]
Carlos, in your article, you have shown a way to add streamlink into a ready made TVH Docker image. Do you know if there's an Docker image also ready with the streamlink install available?

**Comment by cgomesu** [comment]
I don't think there's one readily available (it's kind of a nichey use of tvheadend) but it's pretty simple to build an image for your personal use.  If you want full control, grab a basic and official image (debian/ubuntu/alpine/etc) with just enough pkgs to allow you to build tvheadend from its source, add Streamlink to the container, and then save the container image and use it with any other host machine that has the same architecture.  Of course, managing updates will be more challenging.  Personally, I've been using the linuxserver image on multiple machines now and have never noticed anything weird going on, so I usually recommend it to anyone trying to use the tvhlink integration in a containerized environment.
