### ISSUE TITLE
Reverse proxy Traefik support

### ISSUE THREAD

**Issue by Adito5393** [cgomesu/tvhlink#16]
I have recently managed to configure [Traefik](https://doc.traefik.io/traefik/) as [a systemd service](https://github.com/traefik/traefik/blob/v2.6.3/contrib/systemd/traefik.service) on Rpi4. 
So far, the WebGUI works fine, I still have to test the HTSP port 9982 though.

Would you be interested in a PR with the documentation and the files?
Or you don't want to complicate yourself with maintaining the work of somebody else?

**Comment by cgomesu** [comment]
HI, @Adito5393.  I'm not entirely sure I understand what you want to add to this repo.  Is it a reverse proxy *guide* for TVHeadend?  If this is the case, I feel this would be better suited for the tutorial itself (https://cgomesu.com/blog/Tvhlink/).  For example, you could add a new section before the Conclusion (e.g., TVH reverse proxy) in which you explain how to configure reverse proxies for remote access.  The tutorial itself is on my [website repo](https://github.com/cgomesu/website)--more specifically, in the [_posts/2021-01-17-Tvhlink.md](https://github.com/cgomesu/website/blob/gh-pages/_posts/2021-01-17-Tvhlink.md) file.  To push changes there, fork my website repo, make changes to the tvhlink post `.md` file to include your new section (use github flavored markdown), and then submit a PR to the `gh-pages` of my website repo to start the review process.  (You can preview the website locally using [Jekyll](https://jekyllrb.com/).)

Now, if all you want is to document it here, you can add a section to `README.md` file that describes it.  If it ends up being a lot of info, then I'd prefer that you create a new file to a subdir called `docs` and then edit the `README.md` to mention the new documentation.

All that said, you *really* need to make sure that your connection is encrypted and you have another (more secure) method of auth in place when connecting to TVH remotely.  TVH does not encrypt anything and their default user authentication is not secure.  It is quite possible that you can remedy this via traefik and other reverse proxies but another alternative is to use VPN or Wireguard.  The latter are very secure and allows you to connect remotely as if you were on your private local network.

**Comment by Adito5393** [comment]
Hey,

I like your suggestion to add the info to the blog post. I've heard of Jekyll and I was planning to check it out (I use [Antora](https://antora.org/) a lot and it's super cool). I will take this opportunity to try it out.

The problem that I try to solve is very simple: the setup you recommend VPN + local HTTP is not fast enough to stream 12-13 MB/s. I was using the default PPTP VPN from [my TP-Link C7 router](https://www.tp-link.com/en/home-networking/wifi-router/archer-c7/) & Rpi4 (for headendTV) and it could not stream smoothly.

I didn't even try to set up Wireguard on Rpi4. Do you think it has enough resources to add the Wireguard VPN?
Currently, my Rpi4 (4GB RAM) handles the headendTV + USB TV tuner (USB is sharing the bandwidth with the 1GB ethernet).

**Comment by cgomesu** [comment]
> I like your suggestion to add the info to the blog post. I've heard of Jekyll and I was planning to check it out (I use [Antora](https://antora.org/) a lot and it's super cool). I will take this opportunity to try it out.

sounds good.  when submitting the PR to the website repo, please mention this issue there (via `cgomesu/tvhlink#16`).

> I didn't even try to set up Wireguard on Rpi4. Do you think it has enough resources to add the Wireguard VPN?

Definitely.  Wireguard is a much lighter protocol than OpenVPN (https://duckduckgo.com/?q=wireguard+vs+openvpn+comparison) and PPTP.  If you are running [OpenWrt on your C7](https://openwrt.org/toh/tp-link/archer_c7), you can even add Wireguard there to allow remote access to your entire private network (see https://www.youtube.com/watch?v=04q41GEPvKA, for example).  However, just like OpenVPN, this implementation requires a bit of configuration on each remote device (generate keys and configure wg as VPN), which makes remote access less flexible than using a reverse proxy with basic authentication.
