### ISSUE TITLE
Found matching plugin dash for URL

### ISSUE THREAD

**Issue by loznic89** [cgomesu/tvhlink#17]
hello. would be possible to add streamlink to recognize this argument? in direct installed Linux it recognizes with no problem

2022-09-17 13:47:58.926 spawn: Executing "/usr/bin/env"
2022-09-17 13:48:00.616 spawn: usage: streamlink [OPTIONS]  [STREAM]
2022-09-17 13:48:00.616 spawn: streamlink: error: unrecognized arguments: --ffmpeg-dkey

**Comment by loznic89** [comment]
https://github.com/sunghome/streamlink_optionalkey

**Comment by cgomesu** [comment]
I do not think that argument is supported by the official streamlink
application but you can use any fork instead, like the one you mentioned,
as long as the executable is reachable by TVH.

now, if you want to add such arg to the official app, then you need to ask
the streamlink maintainers on the official github repo.  I do not maintain
the official app.

**Comment by loznic89** [comment]
Sorry i dont know official app is not supported this function.

I want to use that executable (sunghome/streamlink_optionalkey) that unfortunately I have no knowledge to compile it in arm and use it in the raspberry

**Comment by cgomesu** [comment]
> Sorry i dont know official app is not supported this function.

the line `streamlink: error: unrecognized arguments: --ffmpeg-dkey` in the log you posted is telling you that streamlink cannot recognize the argument `--ffmpeg-dkey`.  I just double checked the current options (https://streamlink.github.io/cli.html) and indeed, `--ffmpeg-dkey` is not listed there.

> I want to use that executable (sunghome/streamlink_optionalkey) that unfortunately I have no knowledge to compile it in arm and use it in the raspberry

streamlink is written in Python and such a language is not compiled but interpreted, so all you need is to make sure you have installed the Python dependencies (https://streamlink.github.io/install.html#dependencies), clone the repo, and then ensure your executable is accessible globally (e.g., `/usr/local/bin/streamlink`).  I do not know, howver, if the forked version you mentioned has the same dependencies as the official application, so you might want to check with whoever is maintaining the fork first.
