### ISSUE TITLE
Install other versions of streamlink

### ISSUE THREAD

**Issue by nintiendo1** [cgomesu/tvhlink#27]
First of all, thank you for your work.

I am interested in installing a modified version of streamlink, specifically this one:
https://github.com/Scotto0/streamlink

how can I do it? thank you

**Comment by cgomesu** [comment]
https://github.com/Scotto0/streamlink#-installation

if you want to do it inside the container, you'll have to change the script logic entirely. (install it from pip by allowing it to break system packages and make sure to install it globally; else, the tvh user won't find streamlink).
